## HMM tarining in both a supervised and unsupervised manner

> The provided dataset does not contain a set of sequences, it only contains a list of consecutive days. Thus , I have made an assumption that it contains only one sequence with length of 1000 in the training. Without this assumption, the transition between the states would be meaningless. 

In [90]:
%load_ext autoreload
%autoreload 2

import numpy as np
from HMM import hmm
import os

source_dir = "Dataset/"

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [91]:
# Read and reform the dataset
file_read = open(source_dir+[item for item in os.listdir(source_dir) if ".txt" in item][0], "r+")
lines = file_read.readlines()[1:]
fix_data = lambda line: line.strip().replace('\n', "").split(",")
dataset = np.array(list(map(fix_data, lines)), dtype=object)

In [99]:
# Build and train the model
# Note that in this case the states are refered as the labels and the observations are x values
states = ["foggy", "rainy", "sunny"]
my_model = hmm(states)
my_model.supervised_training(dataset[:, 1], dataset[:, 0])
my_model.viterbi(["yes", "no", "no", "yes", "yes", "yes", "no"])

['rainy', 'foggy', 'foggy', 'rainy', 'rainy', 'rainy', 'sunny']

In [100]:
my_model.likelihood(["no"])

(0.0695244022778892,
 array([[0.    ],
        [0.1807],
        [0.0538],
        [0.462 ],
        [0.    ]]))

In [74]:
milad = np.array([0, 1])
np.insert(milad, -0, 10)

array([10,  0,  1])

In [75]:
np.append(milad, 1

array([ 0,  1, 10])